apiVersion: v1
kind: Service
metadata:
  name: my-nginx-service
spec:
  type: NodePort
  selector:
    app: nginx-dev # Asegura que el servicio seleccione el pod correcto
    env: dev # Asegura que el servicio seleccione el pod correcto
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001 # Se accesa por ip del nodo + este puerto