apiVersion: v1
kind: Service
metadata:
  name: nginx-prod-service
  labels:
    app: nginx-prod
spec:
  type: LoadBalancer
  selector:
    app: nginx-prod # Asegura que el servicio seleccione el deployment correcto
    env: prod # Asegura que el servicio seleccione el deployment correcto
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
      # loadBalancerIP: "X.X.X.X"  # IP estático opcional, si el proveedor lo soporta
  loadBalancerSourceRanges:
    - 0.0.0.0/0
